 devices([
   "iPhone 8 Plus",
   "iPhone 11 Pro Max"
 ])

 languages([
   "en-US",
   "ko"
 ])

project "./Goblin Converter.xcodeproj"
output_directory("./screenshots")
clear_previous_screenshots true